export const hotels = [
  {
    img: './public/assets/images/hotel-1.webp',
    subtitle: 'Hotel 1',
    title: 'Danubius Hotel Regents Park',
    price: 200,
    rating: 4.8,
    popular: true,
  },
  {
    img: './public/assets/images/hotel-2.webp',
    subtitle: 'Hotel 2',
    title: 'The Resident Soho',
    price: 200,
    rating: 4.8,
    popular: true,
  },
  {
    img: './public/assets/images/hotel-3.webp',
    subtitle: 'Hotel 3',
    title: 'London Bridge Hotel',
    price: 200,
    rating: 4.8,
    popular: true,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 4',
    title: 'The Resident Soho',
    price: 120,
    rating: 4.7,
  },
  {
    img: 'https://tophotels.ru/icache/hotel_photos/83/16/311088/2258300_1600x1200.jpg',
    subtitle: 'Hotel 5',
    title: 'Club Prive by Rixos Belek',
    price: 1000,
    rating: 4.83,
  },
  {
    img: 'https://www.coronatours.ru/media/cache/2b/2a/2b2ad65d835b1cec07aba61b6faf8554.jpg',
    subtitle: 'Hotel 6',
    title: 'Avani+ Fares Maldives',
    price: 120,
    rating: 4.7,
  },
  {
    img: 'https://apelsin-tur.ru/wp-content/uploads/2022/10/maldives-water-villa.jpeg',
    subtitle: 'Hotel 7',
    title: 'Conrad Maldives Rangali Island 5',
    price: 900,
    rating: 4.8,
  },
  {
    img: 'https://static.tourvisor.ru/hotel_pics/verybig/4/mardan-palace-102204580.jpg',
    subtitle: 'Hotel 8',
    title: 'TITANIC MARDAN PALACE',
    price: 1200,
    rating: 4.7,
  },
  {
    img: 'https://static.tourvisor.ru/hotel_pics/verybig/4/rixos-hotel-premium-belek-102205540.jpg',
    subtitle: 'Hotel 9',
    title: 'RIXOS PREMIUM BELEK',
    price: 800,
    rating: 4.8,
  },
  {
    img: 'https://blog-cdn.aviata.kz/blog/posts/optimized/0_1db1b9c8b791044c848aa5dbb426d32f514d1869.png.webp',
    subtitle: 'Hotel 10',
    title: 'Atlantis the Palm, ОАЭ',
    price: 720,
    rating: 4.7,
  },
  {
    img: 'https://blog-cdn.aviata.kz/blog/posts/optimized/0_8db0e279071537cc11fac7e532adcc19b3033f87.png.webp',
    subtitle: 'Hotel 11',
    title: 'Marina Bay Sands, Сингапур',
    price: 100,
    rating: 3.8,
  },
]